[package]
name = "diagnostics"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sdk = { path = "../sdk" }
getrandom = { version = "0.2", features = ["custom"] }
log = "0.4"
capnp = "0.19"
once_cell = "1.19"
parking_lot = "0.12"
