[package]
name = "diagnostics"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sdk = { path = "../sdk" }
log = "0.4"
capnp = "0.19"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
once_cell = "1.19"
parking_lot = "0.12"
