[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
sdk = { path = "../modules/sdk" }
futures-timer = "3"

[lib]
crate-type = ["rlib"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
